apiVersion: v1
kind: Pod
metadata:
  name: nginx-loadbalancer
  labels:
    app: nginx-loadbalancer
    name: demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: LoadBalancer
  selector:
    app: nginx-loadbalancer
    name: demo
  ports:
    - port: 80
      targetPort: 80
