apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    course: DevOps
    trainer: Charankumar
spec:
  #list of contaiers
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80